version: '3.8'
services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    environment:
      ORACLE_PWD: oracle
    container_name: to-do-db
    ports:
      - "1521:1521"
    volumes:
      - ./data:/src/data
    restart: always